name: mapper
description: Methods that deal with Maps
version: 0.0.6
publish_to: none
homepage: https://github.com/RagehAz/mapper.git
# --------------------------------------------------------------------------------
environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  # ---------------------------
  cloud_firestore: ^4.0.3
  firebase_database: ^10.0.3
  # ---------------------------
  numeric:
    git:
      url: https://github.com/RagehAz/numeric.git
  # ---------------------------
  #  mockito: ^5.3.2
  # ---------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
# --------------------------------------------------------------------------------
flutter:
# --------------------------------------------------------------------------------
